### PR TITLE
added force modifier

### LINKED ISSUE #2: More force?
Firstly, this is amazing and thank you so much for providing it. I was wondering if there is a way to increase the force on the fingers. So it would bend at a higher threshold of force.

### PR DESCRIPTION
**Pull request by A1igator**
I believe this works.

### CODE REVIEW

**Review by oxters168 — CHANGES_REQUESTED** [review]
This looks really good, and I really appreciate the comment you put to describe the variable. There is only one thing I'd have changed and that is the name of the variable. There is another force applied to the wrist that is separate from the fingers. So to make it more clear, I'd rather the name of this variable be called fingerForce or something similar that is more specific.

**Comment by A1igator** [comment]
Makes sense. Fixed. (Sorry for the force pushes. I messed up my history a bit)

**Review by oxters168 — APPROVED** [review]
Looks great, thanks so much for adding a contribution!

**Comment by A1igator** [comment]
The least I can do for using your awesome work!

**Pull request merged**
